[tool.poetry]
name = "Flask-Session2"
version = "1.3.2"
description = "Adds server-side session support to your Flask application"
authors = ["Shipeng Feng <fsp261@gmail.com>"]
maintainers=["Christopher Pickering"]
repository="https://github.com/christopherpickering/flask-session2"
homepage="https://github.com/christopherpickering/flask-session2#readme"
license = "BSD"
readme="README.md"
classifiers=[
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 2',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ]
packages=[{ include = 'flask_session'}]

[tool.poetry.urls]
"Issue Tracker" = "https://github.com/christopherpickering/flask-session2/issues"

[tool.poetry.dependencies]
python = "^3.7.2"
Flask = "^2.2.2"
cachelib = "^0.13.0"
pytz = "^2022.2.1"

[tool.poetry.dev-dependencies]
black = "^23.0.0"
isort = "^5.10.1"
pymongo = "^4.2.0"
Flask-SQLAlchemy = "^3.0.0"
pymemcache = "^4.0.0"
mypy = "^1.0.0"
pylint = "^2.14.5"
tox = "^4.0.0"
types-redis = "^4.3.14"
redis = "^5.0.0"
coverage = "^7.0.0"
elasticsearch = "^8.3.3"
types-pytz = "^2022.1.2"
google-cloud-datastore = "^2.8.1"
types-requests = "^2.28.8"
google-cloud-firestore = "^2.6.1"
peewee = "^3.15.1"
boto3 = "^1.24.54"
pylint-print = "^1.0.0"
bandit = "^1.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
max_line_length = 99
quiet = true

[tool.isort]
profile = "black"
quiet = true

[tool.pylint.messages_control]
disable = "W0702,R0903,C0415,C0103,R0913,E0602,C0116,C0115,R1710,W0223,R0914,R0902,C0302,R0915, W0719"
[tool.pylint.MASTER]
# load-plugins="pylint_print"
